apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "{{ .Release.Name }}"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    zookeeper:
      nodes:
        - host: keeper-clickhouse-keeper
          port: 2181
    users:
      default/networks/ip: "::/0"
      default/profile: "default"
      default/quota: "default"
      default/password: ""
    clusters:
      - name: "cluster"
        layout:
          shardsCount: {{ .Values.clickhouseCluster.shardsCount }}
          replicasCount: {{ .Values.clickhouseCluster.shardsCount }}
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: {{ .Values.clickhouseCluster.storageClassName }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouseCluster.dataStorage }}
      - name: log-volume-template
        spec:
          storageClassName: {{ .Values.clickhouseCluster.storageClassName }}
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.clickhouseCluster.logStorage }}
