{{- if .Values.tcpLoadBalancer.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-tcp
spec:
  type: LoadBalancer
  ports:
    - name: tcp-native
      port: 9000
      protocol: TCP
      targetPort: {{ .Values.tcpLoadBalancer.targetPort }}
  selector:
    clickhouse.altinity.com/chi: clickhouse
  {{- end }}