apiVersion: v1
kind: Service
metadata:
  name: clickhouse-tcp
spec:
  type: LoadBalancer
  ports:
    - name: tcp-native
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    clickhouse.altinity.com/chi: clickhouse
