{{- if .Values.tlsSecret.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-tls
#   namespace: { { .Values.namespace } }
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.tlsSecret.certs.tlsCrt | b64enc }}
  tls.key: {{ .Files.Get .Values.tlsSecret.certs.tlsKey | b64enc }}
{{- end }}